export const ADD_SUBCONTRACTOR = 'ADD_SUBCONTRACTOR';
export const SUBCONTRACTOR_NAME = 'SUBCONTRACTOR_NAME';
export const SUBCONTRACTOR_CODE = 'SUBCONTRACTOR_CODE';
export const SUBCONTRACTOR_CONTACT_PERSON = 'SUBCONTRACTOR_CONTACT_PERSON';
export const SUBCONTRACTOR_CONTACT_ADDRESS = 'SUBCONTRACTOR_CONTACT_ADDRESS';
export const SUBCONTRACTOR_PHONE = 'SUBCONTRACTOR_PHONE';
export const SUBCONTRACTOR_EMAIL = 'SUBCONTRACTOR_EMAIL';
